name: EchoTell
main: me.cnaude.plugin.EchoTell.EchoTell
version: 0.3.0
authors: 
- cnaude
- modwizcode
commands:
  t:
    description: Sends a message to another player
    usage: /t [player] [message]
  r:
    description: Reply to a message sent with /t
    usage: /r [message]
    aliases: [reply]
permissions:
  echotell:
    description: Use /t [player] [message] and /r [message]
  echotell.use:
    description: Use /t [player] [message] and /r [message]